version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"  # Map port 4000
    environment:
      - PORT=4000         # Set the PORT
      - MONGO_URI=mongodb://mongo:27017/todo-app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

